package com.ninjaone.backendinterviewproject.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.ninjaone.backendinterviewproject.BackendInterviewProjectApplication;
import com.ninjaone.backendinterviewproject.model.Device;
import com.ninjaone.backendinterviewproject.service.DeviceService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.internal.verification.VerificationModeFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.AutoConfigureDataJpa;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Optional;

import static com.ninjaone.backendinterviewproject.controller.DeviceController.REQUEST_URL;
import static org.hamcrest.CoreMatchers.is;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = {BackendInterviewProjectApplication.class})
@WebMvcTest(DeviceController.class)
@AutoConfigureMockMvc
@AutoConfigureDataJpa
public class DeviceControllerTest {
    public static final Long ID = 12345L;
    @Autowired
    ObjectMapper objectMapper;
    @Autowired
    private MockMvc mockMvc;
    @MockBean
    private DeviceService service;

    private Device testEntity;

    @BeforeEach
    void setup() {
        testEntity = new Device(ID, "device", "machine");
    }

    @Test
    void getEntity() throws Exception {
        when(service.getEntity(ID)).thenReturn(Optional.of(testEntity));

        mockMvc.perform(get(REQUEST_URL + ID))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.data.systemName", is("device")));

        verify(service, VerificationModeFactory.times(1))
                .getEntity(ID);
    }

    @Test
    void getEntity_InvalidID() throws Exception {
        mockMvc.perform(get(REQUEST_URL + 999L))
                .andExpect(status().isNotFound())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.message", is("Device Not Found")));

        verify(service, VerificationModeFactory.times(1))
                .getEntity(999L);
    }

    @Test
    void createEntity() throws Exception {
        when(service.saveEntity(any())).thenReturn(testEntity);
        testEntity.setId(null);
        String entityAsString = objectMapper.writeValueAsString(testEntity);
        mockMvc.perform(post(REQUEST_URL)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(entityAsString))
                .andExpect(status().isCreated())
               // .andExpect(content().string(entityAsString));// does not work on autogenerated ids
                .andExpect(jsonPath("$.data.deviceType", is("machine")))
                .andExpect(jsonPath("$.data.systemName", is("device")));
    }

    @Test
    void createEntity_failsOnProvidedId() throws Exception {
        when(service.saveEntity(any())).thenReturn(testEntity);
        String entityAsString = objectMapper.writeValueAsString(testEntity);
        mockMvc.perform(post(REQUEST_URL)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(entityAsString))
                .andExpect(status().is4xxClientError())
                .andExpect(jsonPath("$.message", is("Error creating device")));
    }

    @Test
    void createEntity_failsOnNonProvidedData() throws Exception {
        when(service.saveEntity(any())).thenReturn(testEntity);
        testEntity.setDeviceType(null);
        String entityAsString = objectMapper.writeValueAsString(testEntity);
        mockMvc.perform(post(REQUEST_URL)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(entityAsString))
                .andExpect(status().is4xxClientError())
                .andExpect(jsonPath("$.message", is("Error creating device")));
    }

    @Test
    void deleteEntity() throws Exception {
        doNothing().when(service).deleteEntity(ID);

        mockMvc.perform(delete(REQUEST_URL + ID))
                .andExpect(status().isNoContent());
    }
}
