INSERT INTO DEVICE_TYPE (TYPE_NAME) VALUES ('ANY');
INSERT INTO DEVICE_TYPE (TYPE_NAME) VALUES ('MAC');
INSERT INTO DEVICE_TYPE (TYPE_NAME) VALUES ('WINDOWS WORKSTATION');
INSERT INTO DEVICE_TYPE (TYPE_NAME) VALUES ('WINDOWS SERVER');
INSERT INTO DEVICE_TYPE (TYPE_NAME) VALUES ('LINUX SERVER');


INSERT INTO DEVICE (CUSTOMER, SYSTEM_NAME, TYPE_ID)
VALUES ('marcus', 'Marcus PC', (SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'MAC' LIMIT 1) );
INSERT INTO DEVICE (CUSTOMER, SYSTEM_NAME, TYPE_ID)
VALUES ('marcus', 'Marcus PC2', (SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'MAC' LIMIT 1) );
INSERT INTO DEVICE (CUSTOMER, SYSTEM_NAME, TYPE_ID)
VALUES ('marcus', 'Marcus PC3', (SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'MAC' LIMIT 1) );
INSERT INTO DEVICE (CUSTOMER, SYSTEM_NAME, TYPE_ID)
VALUES ('marcus', 'Marcus Server', (SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'WINDOWS SERVER' LIMIT 1) );
INSERT INTO DEVICE (CUSTOMER, SYSTEM_NAME, TYPE_ID)
VALUES ('marcus', 'Marcus Server2', (SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'WINDOWS SERVER' LIMIT 1) );

INSERT INTO SERVICE (SERVICE_NAME) VALUES ('ANTIVIRUS');
INSERT INTO SERVICE (SERVICE_NAME) VALUES ('BACKUP');
INSERT INTO SERVICE (SERVICE_NAME) VALUES ('PSA');
INSERT INTO SERVICE (SERVICE_NAME) VALUES ('SCREEN SHARE');
INSERT INTO SERVICE (SERVICE_NAME) VALUES ('DEVICE');

INSERT INTO SERVICE_COST (COST , DEVICE_TYPE_ID , SERVICE_ID )
VALUES (5.0,(SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'WINDOWS WORKSTATION' LIMIT 1), (SELECT ID FROM SERVICE WHERE SERVICE_NAME =
'ANTIVIRUS' LIMIT 1) );

INSERT INTO SERVICE_COST (COST , DEVICE_TYPE_ID , SERVICE_ID )
VALUES (5.0,(SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'WINDOWS SERVER' LIMIT 1), (SELECT ID FROM SERVICE WHERE SERVICE_NAME =
'ANTIVIRUS' LIMIT 1) );

INSERT INTO SERVICE_COST (COST , DEVICE_TYPE_ID , SERVICE_ID )
VALUES (7.0,(SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'MAC' LIMIT 1), (SELECT ID FROM SERVICE WHERE SERVICE_NAME =
'ANTIVIRUS' LIMIT 1) );

INSERT INTO SERVICE_COST (COST , DEVICE_TYPE_ID , SERVICE_ID )
VALUES (3.0, (SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'ANY' LIMIT 1), (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'BACKUP' LIMIT 1) );

INSERT INTO SERVICE_COST (COST , DEVICE_TYPE_ID , SERVICE_ID )
VALUES (2.0, (SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'ANY' LIMIT 1), (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'PSA' LIMIT 1) );

INSERT INTO SERVICE_COST (COST , DEVICE_TYPE_ID , SERVICE_ID )
VALUES (1.0,(SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'ANY' LIMIT 1), (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'SCREEN SHARE' LIMIT
1) );

INSERT INTO SERVICE_COST (COST , DEVICE_TYPE_ID , SERVICE_ID )
VALUES (4.0,(SELECT ID FROM DEVICE_TYPE WHERE TYPE_NAME = 'ANY' LIMIT 1), (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'DEVICE' LIMIT
1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 1, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'ANTIVIRUS' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 1, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'BACKUP' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 1, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'SCREEN SHARE' LIMIT 1) );


INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 2, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'ANTIVIRUS' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 2, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'BACKUP' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 2, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'SCREEN SHARE' LIMIT 1) );


INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 3, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'ANTIVIRUS' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 3, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'BACKUP' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 3, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'SCREEN SHARE' LIMIT 1) );


INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 4, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'ANTIVIRUS' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 4, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'BACKUP' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 4, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'SCREEN SHARE' LIMIT 1) );


INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 5, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'ANTIVIRUS' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 5, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'BACKUP' LIMIT 1) );

INSERT INTO SERVICES_BY_DEVICES (CUSTOMER , DEVICE_ID , SERVICE_ID)
VALUES ('marcus', 5, (SELECT ID FROM SERVICE WHERE SERVICE_NAME = 'SCREEN SHARE' LIMIT 1) );

